In [1]:
import pandas as pd
import numpy as np
from math import nan

In [2]:
sheet1 = pd.read_excel(r'.\Noki - Internship (Signals To Review) Project 2.xlsx', 
                        sheet_name='Sheet1', 
                        header=1,
                        nrows=108)
sheet1_questions = pd.read_excel(r'.\Noki - Internship (Signals To Review) Project 2.xlsx', 
                                 sheet_name='Sheet1',
                                 header=None, nrows=1)

In [3]:
def melt_signals(file_path, sheet_name, nrows, first_col_iterate = 6):
    #---- Getting the file ----
    sheet = pd.read_excel(file_path, 
                        sheet_name=sheet_name, 
                        header=1,
                        nrows=nrows)
#     sheet1_questions = pd.read_excel(r'.\Noki - Internship (Signals To Review) Project 2.xlsx', 
#                                      sheet_name='Sheet1',
#                                      header=None, nrows=1)

    columns_to_melt = [[] for i in range(7)]
    for i in range(first_col_iterate, len(sheet.columns)):
        columns_to_melt[(i-first_col_iterate)%7].append(sheet.columns[i])
        
    #---- Melting data ----
    melted_sheet = pd.DataFrame()
    column_names = [
        'Answer',
        'Details',
        'Quotes',
        'Evidence',
        'Incorrect',
        'Partial / Whole',
        'Inaccuracy reason'
    ]
    i = 0
    for group in columns_to_melt:
        melted_group = pd.melt(sheet, 
                               id_vars = sheet.columns[list(range(0, first_col_iterate))], 
                               value_vars=group, 
                               value_name=column_names[i])
        if i == 0:
            melted_sheet = melted_group
        else:
            melted_sheet[column_names[i]] = melted_group[column_names[i]]
        i += 1
    melted_sheet.rename(columns={'variable': 'Question'}, inplace=True)
    melted_sheet.head()
    
# #     ---- Processing data ----
    melted_sheet['Incorrect'] = melted_sheet['Incorrect'].apply(lambda x: False if x in ['False ', 'FALSE ', 0] else
                                                              (True if x == 1 else
                                                              ("" if np.isnan(x) else x)))
    
    
    return melted_sheet

In [4]:
path = r'.\Noki - Internship (Signals To Review) Project 2.xlsx'
sheet1 = melt_signals(path, 'Sheet1', 108, first_col_iterate = 7)
sheet2 = melt_signals(path, 'Sheet2', 118)
sheet3 = melt_signals(path, 'Sheet3', 98)

C:\Users\meuge\AppData\Local\Temp\ipykernel_23684\2264653468.py:28: FutureWarning: This dataframe has a column name that matches the 'value_name' column name of the resulting Dataframe. In the future this will raise an error, please set the 'value_name' parameter of DataFrame.melt to a unique name.
  melted_group = pd.melt(sheet,
C:\Users\meuge\AppData\Local\Temp\ipykernel_23684\2264653468.py:28: FutureWarning: This dataframe has a column name that matches the 'value_name' column name of the resulting Dataframe. In the future this will raise an error, please set the 'value_name' parameter of DataFrame.melt to a unique name.
  melted_group = pd.melt(sheet,
C:\Users\meuge\AppData\Local\Temp\ipykernel_23684\2264653468.py:28: FutureWarning: This dataframe has a column name that matches the 'value_name' column name of the resulting Dataframe. In the future this will raise an error, please set the 'value_name' parameter of DataFrame.melt to a unique name.
  melted_group = pd.melt(sheet,

In [5]:
def upload_frames(filepath, dataframes, names = []):
    writer = pd.ExcelWriter(filepath)

    # Write each DataFrame to a separate spreadsheet
    k = 1
    for i in dataframes:
        i.to_excel(writer, sheet_name=f'Sheet{k}')
        k += 1
    writer.save()

In [6]:
filtered_1 = sheet1.loc[sheet1['Update whether you should do them'] == "Yes"]
filtered_1 = filtered_1.drop('Update whether you should do them', axis = 1)
# filtered_1['Sheet'] = ['Sheet1']
filtered_2 = sheet2.loc[sheet2['Person responsible'] != "Out of scope"]
filtered_3 = sheet3.loc[sheet3['Person responsible'] != "Out of scope"]

combined = pd.concat([filtered_1, filtered_2, filtered_3], axis = 1)
print(filtered_1.info())
print(filtered_2.info())
print(filtered_3.info())
print(combined.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 424 entries, 0 to 852
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   #                   424 non-null    int64
 1   Done?               424 non-null    float64
 2   Person responsible  424 non-null    object
 3   Name                424 non-null    object
 4   Url                 424 non-null    object
 5   LinkedIn            424 non-null    object
 6   Question            424 non-null    object
 7   Answer              343 non-null    object
 8   Details             414 non-null    object
 9   Quotes              416 non-null    object
 10  Evidence            416 non-null    object
 11  Incorrect           424 non-null    object
 12  Partial / Whole     112 non-null    object
 13  Inaccuracy reason   116 non-null    object
dtypes: float64(1), int64(1), object(12)
memory usage: 65.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 495 entries, 0 to 998
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   #                   495 non-null    int64
 1   Done?               495 non-null    float64
 2   Person responsible  495 non-null    object
 3   Name                495 non-null    object
 4   Url                 495 non-null    object
 5   LinkedIn            495 non-null    object
 6   Question            495 non-null    object
 7   Answer              114 non-null    object
 8   Details             495 non-null    object
 9   Quotes              495 non-null    object
 10  Evidence            495 non-null    object
 11  Incorrect           495 non-null    object
 12  Partial / Whole     46 non-null     object
 13  Inaccuracy reason   47 non-null     object
dtypes: float64(1), int64(1), object(12)
memory usage: 74.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 315 entries, 0 to 632
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   #                   315 non-null    int64
 1   Done?               301 non-null    object
 2   Person responsible  315 non-null    object
 3   Name                315 non-null    object
 4   Url                 315 non-null    object
 5   LinkedIn            315 non-null    object
 6   Question            315 non-null    object
 7   Answer              291 non-null    object
 8   Details             315 non-null    object
 9   Quotes              315 non-null    object
 10  Evidence            315 non-null    object
 11  Incorrect           315 non-null    object
 12  Partial / Whole     83 non-null     object
 13  Inaccuracy reason   83 non-null     object
dtypes: int64(1), object(13)
memory usage: 45.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 784 entries, 0 to 534
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   #                   424 non-null    float64
 1   Done?               424 non-null    float64
 2   Person responsible  424 non-null    object
 3   Name                424 non-null    object
 4   Url                 424 non-null    object
 5   LinkedIn            424 non-null    object
 6   Question            424 non-null    object
 7   Answer              343 non-null    object
 8   Details             414 non-null    object
 9   Quotes              416 non-null    object
 10  Evidence            416 non-null    object
 11  Incorrect           424 non-null    object
 12  Partial / Whole     112 non-null    object
 13  Inaccuracy reason   116 non-null    object
 14  #                   495 non-null    float64
 15  Done?               495 non-null    float64
 16  Person responsible  495 non-null    object
 17  Name                495 non-null    object
 18  Url                 495 non-null    object
 19  LinkedIn            495 non-null    object
 20  Question            495 non-null    object
 21  Answer              114 non-null    object
 22  Details             495 non-null    object
 23  Quotes              495 non-null    object
 24  Evidence            495 non-null    object
 25  Incorrect           495 non-null    object
 26  Partial / Whole     46 non-null     object
 27  Inaccuracy reason   47 non-null     object
 28  #                   315 non-null    float64
 29  Done?               301 non-null    object
 30  Person responsible  315 non-null    object
 31  Name                315 non-null    object
 32  Url                 315 non-null    object
 33  LinkedIn            315 non-null    object
 34  Question            315 non-null    object
 35  Answer              291 non-null    object
 36  Details             315 non-null    object
 37  Quotes              315 non-null    object
 38  Evidence            315 non-null    object
 39  Incorrect           315 non-null    object
 40  Partial / Whole     83 non-null     object
 41  Inaccuracy reason   83 non-null     object
dtypes: float64(5), object(37)
memory usage: 263.4+ KB
None

In [7]:
combined = pd.concat([filtered_1, filtered_2, filtered_3], axis = 0)

print(combined.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1234 entries, 0 to 632
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   #                   1234 non-null   int64
 1   Done?               1220 non-null   object
 2   Person responsible  1234 non-null   object
 3   Name                1234 non-null   object
 4   Url                 1234 non-null   object
 5   LinkedIn            1234 non-null   object
 6   Question            1234 non-null   object
 7   Answer              748 non-null    object
 8   Details             1224 non-null   object
 9   Quotes              1226 non-null   object
 10  Evidence            1226 non-null   object
 11  Incorrect           1234 non-null   object
 12  Partial / Whole     241 non-null    object
 13  Inaccuracy reason   246 non-null    object
dtypes: int64(1), object(13)
memory usage: 144.6+ KB
None

In [8]:
upload_frames('.\\update.xlsx', [sheet1, sheet2, sheet3, combined])